version: '3.9'

services:
  pg:
    image: postgres:13-alpine
    container_name: pg_bot
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  redis:
     image: redis:7
     container_name: redis_bot
     env_file:
      - .env

  bot:
    build:
      context: .
    env_file:
      - .env
    container_name: ocr_bot
    command: sh -c "alembic upgrade head && python3 bot.py"
    depends_on:
      - pg
      - redis